### ISSUE TITLE
Clean environment variables

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#18]
Remove all environment variables and path variable into a environment file.

```python
from os import environ

ENVIRONMENT_VARIABLE = Path(environ.get("ENVIRONMENT_VARIABLE", "optional_default_value"))
```

## Tasks

- [x] Identify all environment variables
- [x] Put them into one single environment file
- [x] Import the variable from the environment file
- [x] Replace occurences of `os.path` by `pathlib.Path`
