### ISSUE TITLE
Project workflow

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#3]
Setup a working workflow for code.

## Tasks

- [x] Code quality (flake8)
- [x] Unit tests (pytests)
- [ ] Package build (poetry)
- [ ] Package push (poetry)
- [ ] Dockerize
