### ISSUE TITLE
Fill dataset with interpolation

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#41]
Some videos inside the dataset have holes (with nan values). Instead of filling the holes with 0, use an interpolation function to fille the missing postures by calculating the interpolation between the first missing -1 and the last missing +1.

> For the first interpolation, use the last line value.

## Tasks

- [x] Identify number of holes inside one choregraphy
- [x] Compute the interpolation between inside the hole
- [x] :test_tube: Check if existing choregraphy are working well with interpolation
- [x] Re-preprocess the dataset
