### ISSUE TITLE
Full scale cloud run

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#42]
Setup a cloud instance to run the workflow on the entire dataset.

## Task preparation

- [ ] Implement model train backup callback
- [ ] Implement auto train script
- [ ] Easy way to retrieve artifacts

## Tasks

- [ ] Upload the preprocess dataset on a google storage bucket
- [x] Setup project on Docker container
- [x] Run first training
