### ISSUE TITLE
Setup model build and summary export

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#43]
As we quickly iterate over the model architecture, it could be a good idea to configure an export utilities to save the model architecture, summary, and name into a dictionnary. This will allow us to load the model architecture later to check what can be achieved.

## Tasks

- [x] Refactor the workflow with clean command line arguments
- [x] Export the model as keras serialized dictionnary
- [x] Export the model summary and name
- [x] Automatically add the model to the list of models
- [ ] If the model name exists, add implementation number (unless `--override` specified)
