### ISSUE TITLE
Instantiate scaler for audio preprocessing

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#44]
Instantiate a MinMax scaler for the audio preprocessing. Export the scaler to ensure the pipeline can be applied when predicting.

## Tasks

- [ ] Instantiate model inside sklearn pipeline
- [ ] Run scaling inside pipeline
- [ ] :test_tube: Ensure pipeline is working inside full pipeline
- [ ] :rocket: Add export functions from the #43 feature
