### ISSUE TITLE
Implement chunk training

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#45]
We are currently translating the audio to read all data one after the other, while keeping the dimensionality of the columns.

## Tasks

- [ ] Preprocess the data into chunk
- [ ] Adapt training algorithm
- [ ] :test_tube: Test if the training work on the new dataset
