### ISSUE TITLE
Experiment with custom loss

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#51]
Replace the custom loss function with a custom loss function. The new function computes the mean displacement of each point between each frame, to penalize too large movements (teleportation like movement), and too small movement.

## Tasks

- [ ] Compute mean displacement on the dataset
- [x] Apply custom loss to the training algorithm
- [ ] :test_tube: Test results
