### ISSUE TITLE
Improve cloud training

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#52]
Currently, the cloud training is launched with the terminal, and the terminal cannot be killed. It's also quite slow, and lacks metrics and stability. The saved model is a kera model, and cannot use the predict functions.

Although the checkpoints are saved, there is no easy way to resume training. Therefore it must be implemented. The workflow will be the following.

1. Start training a model with the model name for backup
2. At each epoch, save the backup locally and on mlflow
3. If the training starts and finds a backup with the model name, it loads the backup
4. Unless a `--retrain` was specified
5. At the end of the training, delete the model backup

## Tasks

- [x] Add logs to mlflow
- [x] Improve model export (save in mlflow)
- [x] Introduce checkpoint resume
- [ ] :rocket: When merging on main, redeploy the docker image
- [ ] :rocket: Launch train in background, callback to slack chanel
- [x] :rocket: Attach a graphic card to the container, check performances
