### ISSUE TITLE
Implement transitions between choregraphies

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#56]
During the **dataset preprocessing**, between each choregraphy, append a transition with silent sound. The posture must be an interpolation between the last posture of the choregraphy, and the standing pose. Also add a transition at the begining from the standing posture to the first choregraphy move.

## Tasks

- [x] Add 1 second of silent audio at the begining and end of the audio
- [x] Add 1 second of interpolation at the begining and end of the choregraphy
- [x] :test_tube: Check on the viewer if the choregraphy makes sense
- [x] :test_tube: Run first train and prediction on a subset of the dataset
