### ISSUE TITLE
Finalize cloud workflow

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#58]
Currently the system is run on the cloud like a local machine. The system needs to be finalized to quickly iterate next week.

The backup is downloaded from the `gcp` instance with `scp`. Use the command line to save the model on the gcp bucket, and download the model from the bucket.  
When running the predict, identify if keras or pkl.

The `--with-cloud` needs to be replaced with `--mlflow-track`. The cloud run must use the `tensorflow cloud` package.

## Tasks

- [x] Save the model on the gcp bucket
- [ ] (?) Log metrics to mlflow
- [x] Download the model from the gcp vm
- [ ] :rocket: Test `tensorflow cloud` to run cloud instances
