### ISSUE TITLE
Regroup all new features

### ISSUE THREAD

**Issue by Anatole-DC** [Anatole-DC/koregraph#67]
Branch to regroup all recent features into a clean workflow :
- Audio denoising
- Posture interpolation
- Predict from cloud run

## Tasks

- [ ] Merge #66 into current branch
- [ ] Add `audio_denoising` function to `audio_preprocessing`
- [ ] Add `posture_audio_interpolation` to `dataset_preprocessing`
- [ ] :test_tube: Run train on new preprocessed dataset
